<?php
$idUsuario=null;
$nombreUsuario=null;
$aPaternoUsuario=null;
$aMaternoUsuario=null;
$telefonoFijoUsuario=null;
$telefonoMovilUsuario=null;
$calleUsuario=null;
$numInteriorUsuario=null;
$numExteriorusuario=null;
$coloniaUsuario=null;
$ciudadUsuario=null;
$estadoUsuario=null;
$codigoPostalUsuario=null;
$correoElectronicoUsuario=null;
$loginUsuario=null;
$constrasenaUsuario=null;
$tipoUsuario=null;
?>